apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
spec:
  nodeSelector:
    kubernetes.io/hostname: k8s-node2
  containers:
  - image: mysql:8.0
    name: mysql-container
    volumeMounts:
    - name: host-path
      mountPath: /var/lib/mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "password"
  volumes:
  - name: host-path
    hostPath:
      path: /data_dir/mysql-data #/var/lib/mysql,/data_dir/mysql-data mount
      type: DirectoryOrCreate #DirectoryOrCreate가 아닌 Directory 를 사용하면 해당 디렉토리 사전 생성 필요
